# ------------------------- config.yml -----------------
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20250707-153646-spatial-plot

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline: 
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
# ======== TEXT PROCESSING ==============
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer

# ========= VECTORIZATION ===================
  - name: CountVectorsFeaturizer
  # - name: DIETClassifier
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4

# ====== CORE NLU MODEL =================
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
    hidden_layers_sizes: 
      text: [256, 128]  # Deeper layers for intent/entity separation

# ========= ENHANCEMENTS ====================
  - name: EntitySynonymMapper # MAPS "RM" --> "MYR"
  # - name : FallbackClassifier

  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.4
    ambiguity_threshold: 0.15

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies: 
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.

# ========== CONVERSATION MANAGEMENT ================
  - name: MemoizationPolicy
  - name: RulePolicy # For Strict transacation flows
  - name: UnexpecTEDIntentPolicy
    max_history: 3
    epochs: 100
  - name: TEDPolicy
    max_history: 5 # longer context for multi-step transactions
    epochs: 200
    hidden_layers_sizes:
      text: [256, 128]
      action: [128, 64]

    constrain_similarities: true

  # - name: UnexpecTEDIntentPolicy  # Detect unexpected user inputs
  #   max_history: 5
  #   epochs: 100
